import type { Metadata } from 'next'
import { jakarta } from './ui/fonts'
import './globals.scss'
import { ThemeProvider } from './contexts/ThemeContext'
import { BoardProvider } from './contexts/BoardContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={jakarta.className}>
        <ThemeProvider>
          <BoardProvider>
            <section>
              {children}
            </section>
          </BoardProvider>
        </ThemeProvider>

      </body>
    </html>
  )
}
